{% if theme.adsense %}
    <div>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- new-blog-auto -->
        <ins class="adsbygoogle"
        style="display:block"
        data-ad-client="ca-pub-7536831447654223"
        data-ad-slot="6481460577"
        data-ad-format="auto"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
{% endif %}
